# Generated by Django 5.0.3 on 2024-03-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('family_members_count', models.PositiveIntegerField(verbose_name='تعداد اعضا')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('referrer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی معرف')),
                ('marital_status', models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل'), ('بیوه', 'بیوه'), ('مطلقه', 'مطلقه')], max_length=15, null=True, verbose_name='وضعیت تاهل')),
                ('religion', models.CharField(blank=True, choices=[('تشیع', 'تشیع'), ('تسنن', 'تسنن')], max_length=15, null=True, verbose_name='مذهب')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('coverage', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحت پوشش')),
                ('street_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خیابان')),
                ('route_code', models.IntegerField(blank=True, default=0, max_length=15, null=True, verbose_name='کد مسیر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس دقیق')),
            ],
        ),
    ]
