# Generated by Django 5.0.3 on 2024-03-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedyFolks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='route_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد مسیر'),
        ),
    ]
