# Generated by Django 5.0.3 on 2024-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedyFolks', '0002_alter_needy_route_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='family_members_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد اعضا'),
        ),
    ]
